using System.Web.Mvc;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouMap.Framework.Mvc.RazorHelpers
{
    #line 1 "D:\git\mPower\source\mPower.Framework\Mvc\RazorHelpers\ValidationHelper.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.2.0")]
    public static class ValidationHelper
    {

public static System.Web.WebPages.HelperResult ValidationSummaryWithHtml(this HtmlHelper html)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 4 "D:\git\mPower\source\mPower.Framework\Mvc\RazorHelpers\ValidationHelper.cshtml"
 
    if (!html.ViewData.ModelState.IsValid)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"validation-summary-errors\">\r\n        <ul>\r\n");



#line 9 "D:\git\mPower\source\mPower.Framework\Mvc\RazorHelpers\ValidationHelper.cshtml"
             foreach (var key in html.ViewData.ModelState.Keys)
            {
                foreach (var err in html.ViewData.ModelState[key].Errors)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li>");



#line 13 "D:\git\mPower\source\mPower.Framework\Mvc\RazorHelpers\ValidationHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, html.Raw(err.ErrorMessage));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 14 "D:\git\mPower\source\mPower.Framework\Mvc\RazorHelpers\ValidationHelper.cshtml"
                }
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </ul>\r\n    </div>\r\n");



#line 18 "D:\git\mPower\source\mPower.Framework\Mvc\RazorHelpers\ValidationHelper.cshtml"
    }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
